// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "avito/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PullRequestStorage is an autogenerated mock type for the PullRequestStorage type
type PullRequestStorage struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, pullRequest
func (_m *PullRequestStorage) Create(ctx context.Context, pullRequest domain.PullRequest) error {
	ret := _m.Called(ctx, pullRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PullRequest) error); ok {
		r0 = rf(ctx, pullRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPullRequestByID provides a mock function with given fields: ctx, pullRequestID
func (_m *PullRequestStorage) GetPullRequestByID(ctx context.Context, pullRequestID string) (domain.PullRequest, error) {
	ret := _m.Called(ctx, pullRequestID)

	if len(ret) == 0 {
		panic("no return value specified for GetPullRequestByID")
	}

	var r0 domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.PullRequest, error)); ok {
		return rf(ctx, pullRequestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.PullRequest); ok {
		r0 = rf(ctx, pullRequestID)
	} else {
		r0 = ret.Get(0).(domain.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pullRequestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPullRequestByIDForUpdate provides a mock function with given fields: ctx, pullRequestID
func (_m *PullRequestStorage) GetPullRequestByIDForUpdate(ctx context.Context, pullRequestID string) (domain.PullRequest, error) {
	ret := _m.Called(ctx, pullRequestID)

	if len(ret) == 0 {
		panic("no return value specified for GetPullRequestByIDForUpdate")
	}

	var r0 domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.PullRequest, error)); ok {
		return rf(ctx, pullRequestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.PullRequest); ok {
		r0 = rf(ctx, pullRequestID)
	} else {
		r0 = ret.Get(0).(domain.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pullRequestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByReviewer provides a mock function with given fields: ctx, userID
func (_m *PullRequestStorage) ListByReviewer(ctx context.Context, userID string) ([]domain.PullRequest, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByReviewer")
	}

	var r0 []domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.PullRequest, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.PullRequest); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReplaceReviewer provides a mock function with given fields: ctx, pullRequestID, oldID, newID
func (_m *PullRequestStorage) ReplaceReviewer(ctx context.Context, pullRequestID string, oldID string, newID string) error {
	ret := _m.Called(ctx, pullRequestID, oldID, newID)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, pullRequestID, oldID, newID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusMerged provides a mock function with given fields: ctx, pullRequestID, mergedAt
func (_m *PullRequestStorage) UpdateStatusMerged(ctx context.Context, pullRequestID string, mergedAt *time.Time) error {
	ret := _m.Called(ctx, pullRequestID, mergedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusMerged")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *time.Time) error); ok {
		r0 = rf(ctx, pullRequestID, mergedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPullRequestStorage creates a new instance of PullRequestStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPullRequestStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *PullRequestStorage {
	mock := &PullRequestStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
