// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "avito/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TeamStorage is an autogenerated mock type for the TeamStorage type
type TeamStorage struct {
	mock.Mock
}

// CreateWithMembers provides a mock function with given fields: ctx, team
func (_m *TeamStorage) CreateWithMembers(ctx context.Context, team domain.Team) error {
	ret := _m.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithMembers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Team) error); ok {
		r0 = rf(ctx, team)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWithMembers provides a mock function with given fields: ctx, teamName
func (_m *TeamStorage) GetWithMembers(ctx context.Context, teamName string) (*domain.Team, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetWithMembers")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Team, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Team); ok {
		r0 = rf(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamExists provides a mock function with given fields: ctx, teamName
func (_m *TeamStorage) TeamExists(ctx context.Context, teamName string) (bool, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for TeamExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, teamName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTeamStorage creates a new instance of TeamStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamStorage {
	mock := &TeamStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
